### ISSUE TITLE
It's tricky to make a folder of folders

### ISSUE THREAD

**Issue by casperschipper** [GameOfLife/WFSCollider-Class-Library#1]
(note: not urgent)
The folder button in UScoreEditor expands all the folders instead of grouping them into a folder. 
This is of course as it is designed, but it makes it quite difficult to nest folders in folders.

I can trick the editor by adding a dummy event, because if at least one event is not a folder, it will pack all events in a folder (including any selected folders).

Perhaps more elegant would be two buttons, one for packing & one for unpacking folders ?

**Comment by miguel-negrao** [comment]
> Perhaps more elegant would be two buttons, one for packing & one for unpacking folders ?

Yes, that makes sense. That's quite an easy fix, do you want to have a go at it ?

https://github.com/GameOfLife/Unit-Lib/blob/master/Classes/GUI/Session/UScoreEditorGUI_TopBar.sc#L239

**Comment by casperschipper** [comment]
I just did, I'm still a bit of a tourist when it comes to SuperCollider, thanks for the encouragement :-).
Didn't know how to get a different folder Icon, so I used the word "unfold" instead.

**Comment by miguel-negrao** [comment]
Great, thanks ! I'll merge it in later this week, unless wouter objects.
