### ISSUE TITLE
ERROR: Superclass 'Spherical' of class 'UnitSpherical' is not defined in any file.

### ISSUE THREAD

**Issue by Polkjia** [GameOfLife/WFSCollider-Class-Library#3]
Hello!

I am gettin this error from the console when I start up SC. I am sure I installed WFSC correctly. 
![image](https://user-images.githubusercontent.com/77069555/135081626-e2f97b6a-cd8a-4934-9fe1-b6040078e1b8.png)

How can I solve this problem? I am using windows 10

**Comment by woutersnoei** [comment]
Sorry for the late reply, you need to install the MathLib quark for this. I'm working on making WFSCollider Class Lib into a quark, then dependancies can be loaded automatically in the future..

**Comment by Polkjia** [comment]
Hi there!

> Sorry for the late reply, you need to install the MathLib quark for this. I'm working on making WFSCollider Class Lib into a quark, then dependancies can be loaded automatically in the future..

No problems. I actually figured it out also with the help of my teacher (she is teaching WFS classes). I have other problems tho, I am trying to solve them and then eventually I will come back to you if it doesn't work
