### ISSUE TITLE
Score Save not working on Windows 10 SuperCollider 3.12.2 Install

### ISSUE THREAD

**Issue by carltesta** [GameOfLife/WFSCollider-Class-Library#7]
I'm using the WFSCollider Class Library 2.2.6b in SC 3.12.2 and everything is working great EXCEPT for the Save Score feature. When I try to save a score a dialog box quickly appears and closes immediately. Opening a sound file in a UChain works just fine. It opens a Windows dialog box to select a file and loads it correctly. Any ideas on how to fix this? I'd like to be able to save my work and recall it later.

**Comment by carltesta** [comment]
I've learned a few workarounds for the time being. 
```
//To Save a UScore, run
UScore.current.saveAs;

//To Open a UScore, run
UScore.open(nil, UScoreEditorGUI(_) );
```

**Comment by woutersnoei** [comment]
Hi Carl, thanks for reporting, there have been issues with save/open panels on Windows before, it appears to be a generic SuperCollider issue but hard to debug for me as I don't have any Windows hardware. Good to learn that those workarounds do the job for now. I assume when you use those it does correctly show a save score dialog, right? But perhaps you can help us out a bit here. I just made a change to Unit Lib (dependency of WFSCollider-Class-Lib) to see if that would solve the issue. Could you please try with an updated Unit Lib quark version? Btw is the issue only with the save panel, or also with the open panel?

cheers & thanks,
Wouter

**Comment by carltesta** [comment]
Hi Wouter, Yes, those workarounds work but sometimes the save and open dialogs open don't focus, so I need to focus them by clicking within the open windows of sclang. I just changed my UMenuBarIDE.sc file to correspond with [this change](https://github.com/GameOfLife/Unit-Lib/commit/29f04120bef39625d3fec18231adda8792935856) and it didn't help. This error is effecting both the Save, Save As, and Open functions.

**Comment by woutersnoei** [comment]
Hi Carl, ok could you also try with longer .defer times? It is 0.01 in my change, but would it work with 0.1 instead?

**Comment by carltesta** [comment]
Same result with defer times of 0.1 and 0.9

**Comment by woutersnoei** [comment]
ok, thanks, different approach: I just changed WFSCollider-Class-Library to use the "new" toolbar mode (which I seem to have forgotten before), so that it is actually using the code in UMenuBarIDE ;-). Could you please try with that? And, if it works, also without the { ... }.defer change in Unit Lib? (I have a feeling that it may not be needed)

**Comment by carltesta** [comment]
I changed the WFSLib.sc file but now when I try to startup via WFS.startup, I get the following error:

```
ERROR: Message 'mode_' not understood.
RECEIVER:
class UMenuWindow (0000020349050980) {
  instance variables [19]
    name : Symbol 'UMenuWindow'
    nextclass : instance of Meta_UMixOut (00000203488288C0, size=19, set=5)
    superclass : Symbol 'Object'
    subclasses : nil
    methods : nil
    instVarNames : nil
    classVarNames : instance of SymbolArray (0000020349050B00, size=8, set=2)
    iprototype : nil
    cprototype : instance of Array (0000020349050BC0, size=8, set=3)
    constNames : nil
    constValues : nil
    instanceFormat : Integer 0
    instanceFlags : Integer 0
    classIndex : Integer 624
    classFlags : Integer 0
    maxSubclassIndex : Integer 624
    filenameSymbol : Symbol 'C:\Users\Carl Testa\AppData\Local\SuperCollider\downloaded-quarks\Unit-Lib\Classes\GUI\UMenuWindow.sc'
    charPos : Integer 821
    classVarIndex : Integer 389
}
ARGS:
   Symbol 'toolbar'
CALL STACK:
	DoesNotUnderstandError:reportError
		arg this = <instance of DoesNotUnderstandError>
	Nil:handleError
		arg this = nil
		arg error = <instance of DoesNotUnderstandError>
	Thread:handleError
		arg this = <instance of Thread>
		arg error = <instance of DoesNotUnderstandError>
	Object:throw
		arg this = <instance of DoesNotUnderstandError>
	Object:doesNotUnderstand
		arg this = <instance of Meta_UMenuWindow>
		arg selector = 'mode_'
		arg args = [*1]
	Meta_WFSLib:startup
		arg this = <instance of Meta_WFSLib>
		arg wfsOptions = <instance of WFSOptions>
		arg useMenuWindow = false
		var servers = [*1]
		var o = <instance of WFSMasterOptions>
		var bootFunc = nil
	Interpreter:interpretPrintCmdLine
		arg this = <instance of Interpreter>
		var res = nil
		var func = <instance of Function>
		var code = "WFS.startup;"
		var doc = nil
		var ideClass = <instance of Meta_ScIDE>
	Process:interpretPrintCmdLine
		arg this = <instance of Main>
^^ ERROR: Message 'mode_' not understood.
RECEIVER: UMenuWindow
```

**Comment by woutersnoei** [comment]
oops, sorry about that, should be fixed in the new commit I just made

**Comment by carltesta** [comment]
Yes! This works beautifully. I removed the .defer messages and it still works. I love the new UMenuBarIDE look and functionality. Thank you so much.
